# This image builds kaldi only (without models); Serves as base image for image with acoustic model
#
# Do not use as kaldi image for production setup, it is not optimal (only for demonstration)

# will work on any linux distribution, but we use ubuntu as one of the most popular
FROM ubuntu:16.04

# STAGE 1. BUILDING KALDI. (http://kaldi-asr.org/doc/install.html)

# install git to clone kaldi source
RUN apt-get update && apt-get install -y git 

# cloning kaldi source in /kaldi folder
RUN git clone https://github.com/kaldi-asr/kaldi

# following kaldi/INSTALL instructions to build kaldi

# installing tools (see /kaldi/tools/INSTALL)
# installing dependencies needed to build kaldi (run /kaldi/tools/extras/check_dependencies.sh)
RUN apt-get update && apt-get install -y \
      wget g++ make automake autoconf bzip2 libtool subversion python2.7 python3 \
      libatlas3-base zlib1g-dev 
# building tools
RUN cd /kaldi/tools && make -j

# building kaldi (see /kaldi/src/INSTALL)
RUN cd /kaldi/src && ./configure --shared && make depend -j && make -j

# kaldi is ready; binaries are in /kaldi/src/**bin folders

CMD ["bash"]